app-id: com.aerotechrussia.agp
runtime: org.gnome.Platform
runtime-version: 47
sdk: org.gnome.Sdk
command: AGP
rename-appdata-file: com.aerotechrussia.agp.metainfo.xml

finish-args:
  - --socket=wayland
  - --socket=fallback-x11
  - --socket=pulseaudio
  - --device=all # allow access USB Serial
  - --share=ipc
  - --share=network
  - --filesystem=home
  - --filesystem=xdg-run/gvfs # GVfs
  - --filesystem=/media # automount via udisks
  - --filesystem=/run/udev:ro # enables firmware upload & auto connecting

modules:
  - name: AGP
    sources:
      - type: git
        url: https://github.com/AerotechRussia/AerotechGroundPro.git
        branch: master
    buildsystem: cmake-ninja
    builddir: true
    config-opts:
      - -D BUILD_SHARED_LIBS=OFF
      - -D BUILD_TESTING=OFF
    cleanup:
      - /include
      - /bin/dbf*
      - /bin/shp*
      - /lib/cmake
      - /share/shapelib
      - '*.a'
      - '*.cmake'
